### ISSUE TITLE
HT Cell Proliferation page

### ISSUE THREAD

**Issue by blakeaw** [Borealis-BioModeling/aurora-pkpd#4]
Complete a basic implementation of the HT Cell Proliferation page; `pages/pdanalysis/htproliferation.py`. 

This page will implement some base functionality using the Thunor Core library to load and analyze high-throughput cell proliferation data. We can link to the Thunor Web application for users needing more advanced features and database support.

**Comment by blakeaw** [comment]
Thunor Web app: https://www.thunor.net/

Since it was developed by LoLab at Vandy (which no longer exists), I wonder if the web app is still being maintained or supported.

**Comment by blakeaw** [comment]
Thunor Core: https://github.com/alubbock/thunor

**Comment by alubbock** [comment]
Hi Blake, hope you're well. Yes, trying to maintain Thunor Core and Web as time permits. Feel free to open issues if you find anything amiss or have requests, I'll try to take a look. Cheers, Alex

**Comment by blakeaw** [comment]
Since Thunor Web is still active and supported, I think I'll just add an external tools section and point users to it for HT Cell Proliferation analysis rather than trying to implement a subset of features in the Aurora app. Then, I can focus more on implementing the compartmental modeling and non-compartmental analysis features.

**Comment by blakeaw** [comment]
Addressed in PR https://github.com/Borealis-BioModeling/aurora-pkpd/pull/20
